apiVersion: v1
kind: Service
metadata:
  name: spring-api-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: spring-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
