server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: localhost:29092	
  config:
    activate:
      on-profile: local
  
  datasource:
<<<<<<< HEAD
    url: jdbc:mysql://order-app-db.cobw46ksedm2.us-east-1.rds.amazonaws.com:3306/orderapp 
=======
    url: jdbc:mysql://order-app-db.cobw46ksedm2.us-east-1.rds.amazonaws.com:3306/orderapp
>>>>>>> 0bd8c45952382669b3b7ee89370a17fc6d4c3a51
    username: admin
    password: OrderApp2025!
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
  
