server:
  port: 8081
spring:
  config:
    activate:
      on-profile: local
  
  datasource:
    url: jdbc:mysql://order-app-db.cobw46ksedm2.us-east-1.rds.amazonaws.com:3306/orderapp
    username: admin
    password: OrderApp2025!
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}